---
title: Java 异常总结
copyright: true
date: 2018-08-08 12:31:17
updated:
comments:
tags:
categories:
layout:
permalink:
top:
password:
---

<blockquote class="blockquote-center"> Java 异常总结 </blockquote>

<!--more-->

## 什么是异常？
异常是导致程序中断运行的一种指令流。一旦产生异常之后，异常之后的语句并不会执行，而是直接结束程序，并将错误报告给用户。


## 异常处理格式
注意：捕获更粗的异常要放在捕获更细的异常之后，否则程序**编译**的时候将出错。
![异常处理格式](/upload_image/ExceptionDealFormat.png "异常处理格式")


## Java 异常类的继承结构
> Exception：是程序可以自己处理的异常   
> Error：表示 JVM 错误，一般程序无法处理  

![Java 异常类的继承结构](/upload_image/ExceptionStructure.png "Java 异常类的继承结构")


## Java 的异常处理机制
每当异常产生之后，会在程序中产生一个异常类的实例化对象，之后使用此对象与 catch 中的异常类型相匹配，如果匹配成功，则执行 catch 中的内容，如果匹配不成功，则向下继续匹配，如果都无法成功，程序中出现**中断执行**的问题。
![Java 的异常处理机制](/upload_image/ExceptionDealTheory.png "Java 的异常处理机制")


## throws 与 throw 关键字
> **throws**  
> * 只能在定义**方法**的时候使用，表示该方法不处理异常，而交给调用处进行处理  
> * 格式：`public 返回值类型 方法名称(参数列表...) throws 异常类1,...,异常类n {}`
> * 注意：对于使用 throws 抛出非 RuntimeException 类型的方法，调用方在调用该方法的时候必须进行异常处理，否则编译时报错。如果主方法中使用了 throws 关键字，则表示一切的异常交给 JVM 进行处理，默认的处理方式也是使用 JVM 完成的。**调用方法必须遵循任何可查异常的处理和声明规则。若覆盖一个方法，则不能声明与覆盖方法不同的异常。声明的任何异常必须是被覆盖方法所声明异常的同类或子类，否则编译时报错。**

> **throw**
> * throw 关键字的作用是在程序中抛出一个异常。抛出的时候抛出的是一个异常类的实例化对象。**throw 总是出现在函数体中，用来抛出一个 Throwable 类型的异常。程序会在 throw 语句后立即终止，它后面的语句执行不到，然后在包含它的所有 try 块中「可能在上层调用函数中」从里向外寻找含有与其匹配的 catch 子句的 try 块。**
> * 格式：throw 异常类实例化对象
> * 注意：throw 后面只能跟**一个**异常类实例化对象


## Exception 与 RuntimeException
> **Exception**  
> * Exception 在程序中是必须使用 try...catch 进行处理，否则编译时报错

> **RuntimeException**  
> * RuntimeException 可以不使用 try...catch 进行处理，但是如果有异常产生，则异常将由 JVM 进行处理。


## Java 异常注意事项
> **try 块**  
> * try 块后可接零个或多个 catch 块
> * try 块后至多有一个 finally 块
> * 必须在 try 之后添加 catch 或 finally 块
> * try 块后可同时接 catch 和 finally 块，但至少有一个块
> * 必须遵循块顺序：若代码同时使用 catch 和 finally 块，则必须将 catch 块放在 try 块之后
> * 可嵌套 try-catch-finally 结构
> * 在 try-catch-finally 结构中，可重新抛出异常
> * 一个 try 块可能有多个 catch 块，当匹配到某个 catch 块中的异常类型时，则不会再执行其它 catch 块，转为执行匹配到的 catch 块中的代码
---

> **finally 块**  
> * **当在 try 块或 catch 块中遇到 return 语句时，finally 语句块将在方法返回之前被执行**
> * 在以下4种特殊情况下，finally 块不会被执行：
>> 1.在 finally 语句块中发生了异常「即抛出了一个未处理的异常」  
>> 2.在前面的代码中用了 System.exit(int status); 退出程序  
>> 3.程序所在的线程死亡  
>> 4.关闭 CPU「主要指：计算机断电、失火、遭遇病毒攻击等使得 CPU 停止运行」  


## try、catch、finally语句块的执行顺序  
> 1.当 try 没有捕获到异常时：try 语句块中的语句逐一被执行，程序将跳过 catch 语句块，执行 finally 语句块和其后的语句  
>
> 2.当 try 捕获到异常，catch 语句块里没有处理此异常的情况：当 try 语句块里的某条语句出现异常时，而没有处理此异常的 catch 语句块时，此异常将会抛给 JVM 处理，finally 语句块里的语句还是会被执行，**但 finally 语句块后的语句不会被执行**  
>
> 3.当 try 捕获到异常，catch 语句块里有处理此异常的情况：在 try 语句块中是按照顺序来执行的，当执行到某一条语句出现异常时，程序将跳到 catch 语句块，并与 catch 语句块逐一匹配，找到与之对应的处理程序，其他的 catch 语句块将不会被执行，**而 try 语句块中，出现异常之后的语句也不会被执行，catch 语句块执行完后，执行 finally 语句块里的语句，最后执行 finally 语句块后的语句**

![try、catch、finally语句块的执行顺序](/upload_image/ExceptionNoReturn.png "try、catch、finally语句块的执行顺序")


## try、catch、finally语句块中有 return 后的执行顺序
```Java
public class Test {
    // 当在 try 块或 catch 块中遇到 return 语句时，finally 语句块将在方法返回之前被执行
    public int test() {
        try{
            System.out.println("001");
            // 异常发生跳转到 catch 块中执行代码，其后的所有代码均不再执行
            int temp = 10 / 0;
            return 1;
        }catch (Exception e) {
            System.out.println("002");
            // 在 try 块或 catch 块中遇到 return 语句时，先不着急返回，看看有没有 finally 块，有的话先执行 finally 块，没有则直接返回
            return 2;
        }finally {
            System.out.println("003");
            // 在执行 finally 块的时候直接返回，结束了方法，前面的 try 块或 catch 块均不会再执行
            return 3;
        }
    }

    public static void main(String[] args) {
        int result = new Test().test();
        System.out.println(result);
    }
}
-------------------------------------
程序运行结果：
-------------------------------------
001
002
003
3
```


## 参考博客
[Java 常见异常及解释](http://www.importnew.com/16725.html)
[深入理解 Java 异常处理机制](http://www.importnew.com/14688.html)
